#!/bin/bash

alias ll="ls -lAF"
alias la="ls -aF"
alias lf="ls -FA"
alias e='emacsclient -n'
alias i="idea.sh &"
alias wget="curl -O"
alias grep="grep --color=auto"
alias egrep="egrep --color=auto"
alias ls='gls --color=auto'
