#!/bin/bash

### Environment settings ###
GIT_PROMPT_PATH="/etc/git/git-prompt.sh"
#GIT_COMPLETION_PATH="/usr/local/etc/profile.d/bash_completion.sh"
HUB_COMPLETION_PATH="/etc/git/hub.bash_completion.sh"

### Auto completion ###
# if [ -f ${GIT_COMPLETION_PATH} ]; then
#     source ${GIT_COMPLETION_PATH}
# fi
fpath=($(brew --prefix)/share/zsh/site-functions $fpath)

autoload -U compinit
compinit -u

if [ -f ${HUB_COMPLETION_PATH} ]; then
    source ${HUB_COMPLETION_PATH}
fi

## HUB Alias
if [ `which hub` ]; then
    eval "$(hub alias -s)"
fi

### PS with git ###
if [ -f ${GIT_PROMPT_PATH} ]; then
    source ${GIT_PROMPT_PATH}
    GIT_PS1_SHOWDIRTYSTATE=1
    GIT_PS1_SHOWUPSTREAM=1
    GIT_PS1_SHOWUNTRACKEDFILES=
    GIT_PS1_SHOWSTASHSTATE=1

    setopt PROMPT_SUBST ; PS1='%F{cyan}%n@%m %f%F{magenta}%c%f %F{green}$(__git_ps1 "(%s) ")%f${reset_color}%# '
fi
