#!/bin/bash

### Environment settings ###
GIT_PROMPT_PATH="/etc/git/git-prompt.sh"
GIT_COMPLETION_PATH="/etc/git/git-completion.bash"
HUB_COMPLETION_PATH="/etc/git/hub.bash_completion.sh"

### Auto completion ###
if [ -f ${GIT_COMPLETION_PATH} ]; then
    source ${GIT_COMPLETION_PATH}
fi
if [ -f ${HUB_COMPLETION_PATH} ]; then
    source ${HUB_COMPLETION_PATH}
fi

## HUB Alias
if [ `which hub` ]; then
    eval "$(hub alias -s)"
fi

### PS with git ###
if [ -f ${GIT_PROMPT_PATH} ]; then
    source ${GIT_PROMPT_PATH}
    GIT_PS1_SHOWDIRTYSTATE=1
    GIT_PS1_SHOWUPSTREAM=1
    GIT_PS1_SHOWUNTRACKEDFILES=
    GIT_PS1_SHOWSTASHSTATE=1

    export PS1='\[\033[01;34m\]\W\[\033[00m\]\[\033[00;032m\]$(__git_ps1)\[\033[00m\] % '
fi
