#!/bin/bash

### Environment settings ###
GIT_PROMPT_PATH="${HOME}/.bash/git-prompt.sh"
GIT_COMPLETION_PATH="${HOME}/.bash/git-completion.bash"

### Auto completion ###
fpath=($(brew --prefix)/share/zsh/site-functions $fpath)
zstyle ':completion:*:*:git:*' script ${GIT_COMPLETION_PATH}
autoload -Uz compinit && compinit

### PS with git ###
if [ -f ${GIT_PROMPT_PATH} ]; then
    source ${GIT_PROMPT_PATH}
    GIT_PS1_SHOWDIRTYSTATE=1
    GIT_PS1_SHOWUPSTREAM=1
    GIT_PS1_SHOWUNTRACKEDFILES=
    GIT_PS1_SHOWSTASHSTATE=1

    setopt PROMPT_SUBST ; PS1='%F{cyan}%n@%m %f%F{magenta}%c%f %F{green}$(__git_ps1 "(%s) ")%f${reset_color}
%# '
fi
